<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entities\Entities.csproj" />
    <ProjectReference Include="..\Logging\Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net" Version="3.18.0" />
    <PackageReference Include="Discord.Net.Commands" Version="3.18.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Opus" Version="1.0.0" />
    <PackageReference Include="SpotifyAPI.Web" Version="7.2.1" />
    <PackageReference Include="YoutubeDLSharp" Version="1.1.2" />
    <PackageReference Include="YoutubeExplode" Version="6.5.6" />
  </ItemGroup>

</Project>
